### ISSUE TITLE
Support passing endpoint as URL param

### ISSUE THREAD

**Issue by leomp12** [jsonhero-io/jsonhero-web#13]
To share JSON Hero with dynamic endpoint (e.g. IDs on an REST API documentation) would be necessary to pass endpoint through URL with something like `https://jsonhero.io/new?url=https://someapi.io/v1/id`, right?
It's already possible? If not, wdyt about this feature?

**Comment by ericallam** [comment]
Hey @leomp12, great suggestion! I just added that feature so the above example should work 👍

**Comment by leomp12** [comment]
Wow, awesome! Thanks 😃
