### ISSUE TITLE
Feature Request: Browser Extension

### ISSUE THREAD

**Issue by corbanb** [jsonhero-io/jsonhero-web#33]
This would be insane if it was a browser extension. <3 

LOVE THE WORK!!!

**Comment by ericallam** [comment]
We've recently released a Chrome extension here: https://chrome.google.com/webstore/detail/json-hero/dneionnnnjnofppmhcccbiaklandilch

**Comment by HandsomeOne** [comment]
Will there be a Firefox extension?
