### ISSUE TITLE
Better handle long key names

### ISSUE THREAD

**Issue by ericallam** [jsonhero-io/jsonhero-web#76]
https://jsonhero.io/j/8sJcqWEz7Nek
<img width="1158" alt="Screen Shot 2022-06-08 at 10 10 42" src="https://user-images.githubusercontent.com/534/172578826-9dbcbfea-2232-49f4-8266-f770e310f28a.png">

**Comment by sascha10000** [comment]
Would that be a feasible solution?
![grafik](https://user-images.githubusercontent.com/6839449/172828903-9213d544-9ae3-42a6-8a44-a89cd1a9d7c7.png)

Solution: Add the tailwind classes "text-ellipsis overflow-hidden" to the h2-tag containing the long text, in this case the shown id.

![grafik](https://user-images.githubusercontent.com/6839449/172829340-6dceb850-3aac-48a4-8b28-d5b6312646ab.png)

@Work right now so I have no real time to modify my fork and pr it. Maybe in the evening.
